### ISSUE TITLE
The first line of a nested group is not indented

### ISSUE THREAD

**Issue by edmcman** [afranchuk/prettyprint#1]
When nesting a group that has to be split on multiple lines, the first line is not indented, which I think is a bug.

Here is an example:
``` c++
#include <iostream>

#include "prettyprint.h"

void print_grouped() {
    auto doc = pp::group( pp::nil() +
            "one" + pp::line() +
            "two" + pp::line() +
            "three" + pp::line() +
            "four");

    auto settings = std::cout << pp::set_width(15);
    settings << pp::set_max_indent(4) << doc
             << std::endl << std::endl;

    settings << pp::set_max_indent(4) << pp::nest (4, doc)
             << std::endl << std::endl;
}

int main() {
    print_grouped();

    return 0;
}
```

This results in
```
one
two
three
four

one
    two
    three
    four
```

I expected each line of the group to be indented by the same amount.

**Comment by afranchuk** [comment]
I realize the potential for confusion, however this is the intended behavior. If you read the paper on which this library is based, `nest` means "this content _is nested_ at offset N", not "this content _should be nested_ at offset N". That is to say, it affects any following newlines in layout, but does not affect the immediately following content. This is especially relevant when printing e.g. tree contents when the first item of the tree is printed on the same line but following items are on new lines.

To achieve your desired effect, you'd want to explicitly insert the leading indentation (to "set" the indentation level) and then use `nest` (to indicate the current indentation level). Or add a newline before the first item in the group (though only if you're okay with the extra newline of course).

**Comment by edmcman** [comment]
Thanks, I was just reading the Wadler paper and realized this seems to be intentional, though a bit awkward in my opinion.  Sorry for the noise!

**Comment by edmcman** [comment]
It would be nice if there was a way to add a line that group() would not collapse into a space.  E.g., I might want:

`"[" + nest(4, group(line() + "stuff")) + line() +  "]"`

If it fits, I would want `[stuff]`, not `[ stuff]`.  But if it doesn't fit on one line, I would want:

```
[
    stuff
]
```

**Comment by afranchuk** [comment]
Yep, that's even mentioned in the paper:
> Variants might be considered where each newline carries with it the alternate text it should be replaced by. For instance, some newlines might be replaced by the empty text, others with a single space.

That'd be a fairly simple addition if you wanted to try it out. Otherwise if you do have a need for it I could put something in within the next week. Not mentioned in the paper, but in my opinion you could generalize it further to an arbitrary document which provides two alternatives to try when laying out (i.e. not limited to just newlines).

**Comment by afranchuk** [comment]
Though to be fair, `group` centers around newlines since that is the deciding factor when it decides to flatten things into a single line or not.

**Comment by edmcman** [comment]
> That'd be a fairly simple addition if you wanted to try it out. Otherwise if you do have a need for it I could put something in within the next week. Not mentioned in the paper, but in my opinion you could generalize it further to an arbitrary document which provides two alternatives to try when laying out (i.e. not limited to just newlines).

I'll give that a shot when I am back to work after the holidays.  Thanks!
